project_name: MAID_swint_back
exp_name: T2.0
use_wandb: False
wandb_entity: qbyjj
train_root: E:/FineGrained/datasets/MAID/train/
val_root: E:/FineGrained/datasets/MAID/val/
data_size: 384
num_workers: 1
batch_size: 2
model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 50
warmup_batchs: 800
use_amp: True
use_fpn: False
fpn_size: 1536
use_selection: False
num_classes: 51
coarse_num_classes: 8
finegrain: True
num_selects: 
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: False
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10